services:
  db:
    image: postgres:14
    restart: always
    container_name: btp_postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./scripts/insert_into_wallets.sql:/docker-entrypoint-initdb.d/02_insert_into_wallets.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btp_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
